"""add learning_sessions and achievements tables

Revision ID: 05d2d3871df0
Revises: 5de674e8847f
Create Date: 2026-05-14 12:19:57.995175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05d2d3871df0'
down_revision: Union[str, Sequence[str], None] = '5de674e8847f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('criteria_json', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('learning_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_sessions_user_id'), 'learning_sessions', ['user_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)

    # Seed predefined achievements
    achievements_table = sa.table(
        "achievements",
        sa.column("key", sa.String),
        sa.column("name", sa.String),
        sa.column("description", sa.String),
        sa.column("icon", sa.String),
        sa.column("criteria_json", sa.String),
    )
    op.bulk_insert(
        achievements_table,
        [
            {"key": "first_session", "name": "初次学习", "description": "完成第 1 次学习会话", "icon": "book-open", "criteria_json": '{"type": "total_sessions", "target": 1}'},
            {"key": "streak_3", "name": "三日坚持", "description": "连续学习 3 天", "icon": "flame", "criteria_json": '{"type": "streak_days", "target": 3}'},
            {"key": "streak_7", "name": "一周战士", "description": "连续学习 7 天", "icon": "flame", "criteria_json": '{"type": "streak_days", "target": 7}'},
            {"key": "streak_30", "name": "月度学霸", "description": "连续学习 30 天", "icon": "trophy", "criteria_json": '{"type": "streak_days", "target": 30}'},
            {"key": "hours_10", "name": "十小时俱乐部", "description": "累计学习 10 小时", "icon": "clock", "criteria_json": '{"type": "total_hours", "target": 10}'},
            {"key": "hours_50", "name": "五十小时达人", "description": "累计学习 50 小时", "icon": "star", "criteria_json": '{"type": "total_hours", "target": 50}'},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_learning_sessions_user_id'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_table('achievements')
    # ### end Alembic commands ###
